# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-21 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170126_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='is_static',
            field=models.BooleanField(default=False),
        ),
    ]
